### ISSUE TITLE
Documentation for nvarchar(max), varbinary(max), varchar(max)

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/documentation#10]
https://stackoverflow.com/questions/2496695/can-i-create-a-column-of-nvarcharmax-using-fluentmigrator

I suggest the documentation link to the actual tests that support the explanation, so that users are encouraged to poke around (hopefully contribute!)

The behavior should be based on processor switch.  Ideally documented with a markdown table.

**Comment by fubar-coder** [comment]
I was always under the impression that an `AsString` should always result in a CLOB. Maybe changing this behaviour would be a candidate for 4.0? Would it break something? ... Most likely.

**Comment by jzabroski** [comment]
In SQL Server T-SQL, if you write:

```sql
CREATE TABLE dbo.Foo (
  TextColumn VARCHAR NULL
);
```
then `VARCHAR` is interpreted as `VARCHAR(30)`

Source: https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-2017#remarks
Quote:
> When n isn't specified in a data definition or variable declaration statement, the default length is 1. If n isn't specified when using the CAST and CONVERT functions, the default length is 30.

**Comment by fubar-coder** [comment]
So I guess that it'd be better to keep the current behavior and add a new `AsMaxString` (or something similar) - and a `AsMaxBinary`?

**Comment by jzabroski** [comment]
I don't wish to break the current behavior.  While I think it's incorrect, I doubt many people really would ever want to literally create `int.MaxValue` length strings.  In fact, the current behavior prevents such stupidity and protects C# engineers who may not know any better about database storage internals and the importance of storing large text data out-of-row in a LOB field.
