### ISSUE TITLE
"FluentMigrator.Runner" missing?

### ISSUE THREAD

**Issue by Hefaistos68** [fluentmigrator/documentation#20]
After adding the 3.2.1 nuget package to my project, the FluentMigrator.Runner namespace cant be found. Actually seems I cant find it anywhere. Is that outdated, am I missing something, did I read the doc wrong?

**Comment by Hefaistos68** [comment]
Sorry, got it wrong. didnt read all doc.

**Comment by jzabroski** [comment]
Feel free to ask more questions in the gitter chat.
