### ISSUE TITLE
Build in Azure DevOps

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/documentation#24]
Move docs to Azure Pipelines like the main repo.

**Comment by eloekset** [comment]
I've followed the guide to create a new Azure DevOps project that corresponds to the repo name "documentation" in our GitHub organization, but I'm not able to create the link between a new pipeline in that project to FluentMigrator on GitHub, even though we have the "GitHub App" (Azure Pipelines) installed for all repos of the organization.
![image](https://user-images.githubusercontent.com/791721/84085361-b7887600-a9e5-11ea-89c9-6cecf13b52c3.png)

I think maybe @fubar-coder is the one that must do this initial configuration for us.
![image](https://user-images.githubusercontent.com/791721/84085304-8f991280-a9e5-11ea-99c8-b6d85cbbf0a7.png)

When I get to the last step, I end up with this error message:
![image](https://user-images.githubusercontent.com/791721/84085536-164def80-a9e6-11ea-8e67-d15094a1d2d6.png)

**Comment by jzabroski** [comment]
@eloekset I think i got it working.  I added added a dummy yaml file so you can do your magic

**Comment by eloekset** [comment]
@jzabroski We have a build pipeline that generates the site content to be pushed to the fluentmigrator.github.io repo now.

But there's one thing that's not so easy it seems. Unless you have access to create some kind of token on the organization. I can't see a possibility to do that, but you may have more privileges than I've got. It's possible to store it as a secret variable in the release pipeline.

If not possible, the next best thing I've found is this: https://cloudblogs.microsoft.com/opensource/2019/04/05/publishing-github-pages-from-azure-pipelines/

I've added a Deploy Key that has write access to the repo, but I haven't uploaded the private key anywhere yet, in case we can find a better option.

**Comment by jzabroski** [comment]
I try to save key secrets in my Dashlane account.  But I have not read in depth on how secure Dashlane's sharing feature is.  It's possible I could save the secret key and share it back to you so you have access god forbid Microsoft implodes or something :)

**Comment by eloekset** [comment]
If you edit the release pipeline, I've prepared a variable called GitHubToken that is marked as secret. But I don't want to use a personal token there, so I hoped you had access to generate an organizational token if such thing even exists.
![image](https://user-images.githubusercontent.com/791721/84209026-5a5bf580-aab5-11ea-8fd8-d3afa63fe255.png)

**Comment by jzabroski** [comment]
I believe I added it.

**Comment by eloekset** [comment]
I've done some investigation today:
 - Is there a `git core.autocrlf` config that makes all files look like they've changed, but it's actually just different line endings on every line in every file?
    - Answer: No, I tried all three `core.autocrlf` settings, `true`, `input`, `false`, but it didn't make any difference.
  - This is the output of `git diff HEAD^ manifest.json`:
[git-diff-manifest-json.txt](https://github.com/fluentmigrator/documentation/files/4767069/git-diff-manifest-json.txt)
    - It may tell someone who knows **DocFX** something. One interesting thing to note is that all hash values of all files have changed. That makes me think that further investigation should be done in the build pipeline, where DocFX runs, and not the release pipeline, where I basically just clone a git repo, replace all files with the build artifact and commit all changes.
    - I assume DocFX generate a hash of all output files after building them, and store those hashes in the manifest.json file for some reason. When the hash values in this file are different for all files, it means that DocFX has noticed a change to all files, even before git is involved at all. [About the manifest.json file.](https://dotnet.github.io/docfx/spec/docfx_build_manifest_file.html)

It may even mean that this problem with all files changing only happens once. So if I push the commit to https://github.com/fluentmigrator/fluentmigrator.github.io and make another change to build once more, only the changed file will be committed (as long as Travis is disabled and doesn't commit it's changes again).

**Comment by jzabroski** [comment]
I wonder if we should just march on and do a test commit to see if it continues to create huge diff graphs.  gandarez's commit is still waiting checkin and I wanted to get it merged, anyway.  

Frankly, I want to move away from DocFX and to Dave Gleick's Statiq system, but its not anywhere near my top priority right now.  But I will add it to the roadmap.

**Comment by eloekset** [comment]
Ok, I'll give it a try. The build artifacts look ok when I download an look at them locally, so it shouldn't destroy anything. I hope....

**Comment by eloekset** [comment]
It has published now. I don't see anything unexpected on the hosted site.
Actually all files didn't change. It's easier to see now, when browsing the repo it committed to. Most changes happened to the files in the Api folder, but not all files there either.

The way I've disabled Travis build is this:
![image](https://user-images.githubusercontent.com/791721/84440789-e3e90000-ac3a-11ea-912c-4d2acb6f5736.png)

We should probably just remove the webhook altogether if we choose to stick with the Azure Pipelines for the documentation repo.

**Comment by jzabroski** [comment]
Seems like an appropriate way to disable travis haha

**Comment by eloekset** [comment]
The second commit from Azure DevOps changed only three files: https://github.com/fluentmigrator/fluentmigrator.github.io/commit/cacf6616a6aee8838ad1591c7c1559bf41396c41
But then Travis kicked off again, and we're back to changing hundreds of files on each build: https://github.com/fluentmigrator/fluentmigrator.github.io/commit/e3dcbeb6d92daf3f3978b9b7bf6e3b4cd7e064cb

**Comment by jzabroski** [comment]
How do we terminate the Travis CI build?  I thought I had access to the FluentMigrator TravisCI but i dont.  Can we just delete Travis CI's credentials to GitHub?

**Comment by jzabroski** [comment]
I did the following just now:
- Deleted the WebHook to TravisCI
- Deleted the GitHub App for TravisCI

**Comment by eloekset** [comment]
I found these settings and disabled them now. We'll see on the next commit if it helps.
![image](https://user-images.githubusercontent.com/791721/84529500-da66a300-ace1-11ea-9c6f-5d7523562ee9.png)
