### ISSUE TITLE
Doc for FM.Console strip comments

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/documentation#30]
https://github.com/fluentmigrator/fluentmigrator/issues/956#issuecomment-679927533

**Comment by igitur** [comment]
`FluentMigrator.DotNet.Cli` probably too, but I haven't looked at that yet, because I don't really use that one.

**Comment by jzabroski** [comment]
I definitely updated that one myself.  This was one of the first contributions I made to the project.

What's weird is that it seems like (if I am reading the code correctly) there is no way to not strip comments in the Console?

See: https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Console/MigratorConsole.cs#L264-L268

**Comment by igitur** [comment]
> I definitely updated that one myself. This was one of the first contributions I made to the project.
> 
> What's weird is that it seems like (if I am reading the code correctly) there is no way to not strip comments in the Console?
> 
> See: https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Console/MigratorConsole.cs#L264-L268

There is. See https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Console/Options.cs#L113 

If you append `-` then `v == null`.

**Comment by jzabroski** [comment]
Ah, wow.  I missed that, and it's been a long time since I've used Jonathan's Mono.Options.  Do you have a particular command line arg parsing library you prefer?  We use NateMcMaster.CommandLine.Utils for DotnET CLi tool, and I don't love it.  I also don't love *NIX getopt syntax.  And FluentCommandLineParser has a nasty bug (or design flaw?) with name shadowing.

**Comment by igitur** [comment]
As a user of this library, I'm not particularly partial to any library. When I'm developing, I tend to lean towards CommandLineParser, but just because I know it well.
