### ISSUE TITLE
Dead links on documentation start page

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/documentation#47]
The marked links weren't resolved during build:

![grafik](https://user-images.githubusercontent.com/4739844/127991070-c0164731-5d6f-45d0-b786-d479c414c97d.png)

**Comment by jzabroski** [comment]
I tried to troubleshoot it but couldnt figure it out.  Any idea why they are coming up as deadlinks?  Is there a tool or tricks to debug this effectively

**Comment by fubar-coder** [comment]
No, not that I'm aware of. I always try to look at the docfx output (console) whenever I have this problem.

**Comment by jzabroski** [comment]
Cool.  I just read the documentation on XREF in DocFX and it looks fairly straight-forward to debug the output: https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-between-projects

In effect, look at the xrefmap.yml and see where the faq the docs went :D

**Comment by jzabroski** [comment]
Hmm... xrefmap.yml lists:

```yaml
- uid: faq
  name: FAQ
  href: articles/faq.html
```

Attempting fix now.

**Comment by jzabroski** [comment]
It fixed the faq issue, but the sql-server-quickstart.md file appears to be missing.  I will have to check my laptop - maybe I didnt check it in??
