### ISSUE TITLE
Custom metadata for the VersionInfo table does not work

### ISSUE THREAD

**Issue by rthm93** [fluentmigrator/documentation#6]
According to the article on [**Custom metadata for the VersionInfo table**](https://fluentmigrator.github.io/articles/version-table-metadata.html)
>  In the same assembly that your migrations are located, create a new class (it has to be public) that implements the IVersionTableMetaData interface and decorate the class with the VersionTableMetaDataAttribute. FluentMigrator will automatically find this and use it instead of the default settings.

Is this still relevant? I have tested this out and it is not working in FluentMigrator v3.1.3. 

In order to use custom metadata for VersionInfo table, I copied the code of VersionTable class and then added the class into service collection to override DefaultVersionTableMetaData. 

It was not mentioned here, should we update this to include some code snippets?

The following code worked for me:

VersionInfo table class
```
    public class MyVersionTableMetadata : IVersionTableMetaData
    {
        public object ApplicationContext { get; set; }

        public virtual string SchemaName => "";

        public virtual string TableName => "VersionInfo";

        public virtual string ColumnName => "Version";

        public virtual string UniqueIndexName => "UC_Version";

        public virtual string AppliedOnColumnName => "AppliedOn";

        public virtual string DescriptionColumnName => "Description";

        public virtual bool OwnsSchema => true;
    }
```

Adding into service collection
```
serviceCollection.AddScoped(typeof(IVersionTableMetaData), typeof(MyVersionTableMetadata));
```

**Comment by jzabroski** [comment]
@rthm93 Thanks, I fixed it now.
