### ISSUE TITLE
API documentation cannot be opened

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/documentation#60]
Steps to reproduce.

1. Open https://fluentmigrator.github.io/api/index.html
2. Try to click on "Version 2.x" -> 404
3. Try to click on "Version 3.x" -> Overview doesn't open

What did I expect to happen:

Clicking on "Version 2.x" should open the 2.x documentation.
Clicking on "Version 3.x" should open the 3.x documentation.

**Comment by jzabroski** [comment]
It appears I broke this in #59

**Comment by jzabroski** [comment]
I think I was able to fix it, it was caused by MSBuild plug-in model sucking

**Comment by jzabroski** [comment]
Confirmed resolved.
