### ISSUE TITLE
add documentation for [Maintenance] attribute

### ISSUE THREAD

**Issue by mabead** [fluentmigrator/documentation#8]
I was looking for a way to execute some code whenever my migration runner was executed (the goal being to always refresh my sql views). After some looking around, I found on stackoverflow that the `[Maintenance]` attribute can be used for this. I then looked on https://fluentmigrator.github.io/ but I couldn't find any mention of this attribute. I had to look directly in the source code.

Please update the FluentMigrator documentation. A feature that is not documented is a feature that does not exist... if stackoverflow didn't exist ;)

**Comment by jzabroski** [comment]
Note also, the search bar on the left does not return any search results when you search for the phrase maintenance.  Other phrases to include are beforeall, afterall, beforeeach, aftereach.

Why do we still need Profiles if we have Maintenance migrations?

**Comment by fubar-coder** [comment]
Profiles - IIRC - are used for seeding the database.

**Comment by jzabroski** [comment]
Interesting.

Would it be even more accurate to say Profiles are probably used for seeding the database _per environment_, and the profile name maps to an environment name?  Environment could be customer, or SDLC stage (UnitTest, Dev, Alpha, Beta, Prod), or both.

**Comment by fubar-coder** [comment]
Yes, that's the way it was most likely planned.
